### ISSUE TITLE
Can you explain me something for the labeling

### ISSUE THREAD

**Issue by Panos13L** [siddhi5386/Emotion-Recognition-from-brain-EEG-signals-#2]
How we got 58560 labels?
On this experiment we have 32 participants 40 one-minute video each one and you avarage the data taking 2sec windows
So i expect 32*40*30)=38400 labels

**Comment by AeronZhang** [comment]
(8064-256)/16*40*3=58560

**Comment by AeronZhang** [comment]
(8064-256)/16x40x3=58560
