### ISSUE TITLE
number of classes

### ISSUE THREAD

**Issue by saimohan16** [siddhi5386/Emotion-Recognition-from-brain-EEG-signals-#4]
how did we get the class number as 10 (num_classes = 10) in cell 85. where as we only have binarly class as 0 or 1 in the y_train in cell 75.

**Comment by sibasmarak** [comment]
Hi, the size of `y_train` in [cell 75/76](https://github.com/siddhi5386/Emotion-Recognition-from-brain-EEG-signals-/blob/master/Emotion_recognition_using_CNN.ipynb) is (46848, 10). The task is a multiclass classification problem with 10 classes. Therefore, the `num_classes` is set as 10.

**Comment by saimohan16** [comment]
I printed the unique values from the y_train and got only 2 values from it [0,1].  can you provide more details on it?
